# ═══════════════════════════════════════════════════════════════════════════════
# Database Models for EV Cars Application
# ═══════════════════════════════════════════════════════════════════════════════
# This file defines the database schema using SQLAlchemy ORM (Object-Relational Mapping).
# SQLAlchemy allows us to interact with the database using Python classes instead of
# writing raw SQL queries, making the code more maintainable and secure.
#
# Tables defined:
#   - Admin: Stores administrator credentials for authentication
#   - Customer: Stores customer accounts for personalized experience
#   - Car: Stores electric vehicle listings with details and images
#   - Lead: Stores customer interest/inquiry information
#   - Appointment: Stores scheduled test drive appointments
#   - SavedCar: Links customers to their saved/garage cars
# ═══════════════════════════════════════════════════════════════════════════════

from datetime import datetime
from flask_sqlalchemy import SQLAlchemy

# Initialize SQLAlchemy instance
# This will be connected to the Flask app in api.py using db.init_app(app)
db = SQLAlchemy()


# ─────────────────────────────────────────────────────────────────────────────
# ADMIN MODEL
# ─────────────────────────────────────────────────────────────────────────────
# The Admin model stores administrator accounts for the dashboard.
# Only admins can create, edit, and delete car listings.
#
# Security note: Passwords are never stored in plain text. The password_hash
# field stores a cryptographic hash generated by Werkzeug's generate_password_hash.
class Admin(db.Model):
    __tablename__ = "admin"  # Explicit table name in the database
    
    # Primary key - auto-incrementing unique identifier for each admin
    admin_id = db.Column(db.Integer, primary_key=True)
    
    # Username must be unique to prevent duplicate accounts
    # String(80) limits the username to 80 characters
    username = db.Column(db.String(80), unique=True, nullable=False)
    
    # Hashed password - String(255) accommodates various hash algorithms
    # The hash includes a salt to prevent rainbow table attacks
    password_hash = db.Column(db.String(255), nullable=False)


# ─────────────────────────────────────────────────────────────────────────────
# CUSTOMER MODEL
# ─────────────────────────────────────────────────────────────────────────────
# The Customer model stores customer accounts for the public-facing site.
# Customers can register, login, save cars to their garage, and submit leads.
#
# This is separate from Admin to maintain clear role separation:
#   - Customers: Browse cars, save favorites, submit interest, book test drives
#   - Admins: Manage inventory, view analytics, handle leads/appointments
class Customer(db.Model):
    __tablename__ = "customer"
    
    # Primary key - auto-incrementing unique identifier
    customer_id = db.Column(db.Integer, primary_key=True)
    
    # Customer's display name
    name = db.Column(db.String(100), nullable=False)
    
    # Email must be unique - used for login
    email = db.Column(db.String(120), unique=True, nullable=False)
    
    # Hashed password for secure authentication
    password_hash = db.Column(db.String(255), nullable=False)
    
    # Phone number (optional)
    phone = db.Column(db.String(20), nullable=True)
    
    # Account creation timestamp
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    
    def to_dict(self):
        """
        Convert Customer to dictionary (excludes password_hash for security).
        """
        return {
            "customer_id": self.customer_id,
            "name": self.name,
            "email": self.email,
            "phone": self.phone,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }


# ─────────────────────────────────────────────────────────────────────────────
# CAR MODEL
# ─────────────────────────────────────────────────────────────────────────────
# The Car model represents an electric vehicle listing in the marketplace.
# Each car has details relevant to EV buyers: range, charging time, price, etc.
#
# This model maps to the 'car' table in SQLite and provides:
#   - Automatic ID generation
#   - Type validation through column definitions
#   - JSON serialization via to_dict() method
class Car(db.Model):
    __tablename__ = "car"
    
    # ─────────────────────────────────────────────────────────────────────────
    # Column Definitions
    # ─────────────────────────────────────────────────────────────────────────
    
    # Primary key - unique identifier for each car listing
    car_id = db.Column(db.Integer, primary_key=True)
    
    # Car model name (e.g., "Tesla Model 3", "BMW iX3")
    model = db.Column(db.String(120), nullable=False)
    
    # Manufacturing year - Integer for easy filtering and sorting
    year = db.Column(db.Integer, nullable=False)
    
    # Price in AED (UAE Dirhams) - Float to handle decimal values
    price = db.Column(db.Float, nullable=False)
    
    # Battery range in kilometers - key metric for EV buyers
    range_km = db.Column(db.Integer, nullable=False)
    
    # Fast charging time in minutes (typically 10-80% charge)
    charge_time_min = db.Column(db.Integer, nullable=False)
    
    # Detailed description of the vehicle - Text type for longer content
    description = db.Column(db.Text, nullable=False)
    
    # URL or path to the car's image
    # Can be an external URL or internal path like "/api/uploads/filename.jpg"
    image_url = db.Column(db.Text, nullable=False)
    
    # ─────────────────────────────────────────────────────────────────────────
    # Sales Tracking Fields (Feature 1: Revenue & Analytics)
    # ─────────────────────────────────────────────────────────────────────────
    # Status: 'available' or 'sold' - tracks if car has been sold
    status = db.Column(db.String(20), nullable=False, default='available')
    
    # Final sale price - may differ from listing price due to negotiation
    sale_price = db.Column(db.Float, nullable=True)
    
    # Date when the car was sold - used for revenue over time analytics
    sold_date = db.Column(db.DateTime, nullable=True)

    # ─────────────────────────────────────────────────────────────────────────
    # Serialization Method
    # ─────────────────────────────────────────────────────────────────────────
    def to_dict(self):
        """
        Convert the Car model instance to a dictionary for JSON serialization.
        
        This method is called when returning car data from API endpoints.
        Flask's jsonify() function requires data to be JSON-serializable,
        and SQLAlchemy model instances are not directly serializable.
        
        Returns:
            dict: All car fields as a dictionary
        """
        return {
            "car_id": self.car_id,
            "model": self.model,
            "year": self.year,
            "price": self.price,
            "range_km": self.range_km,
            "charge_time_min": self.charge_time_min,
            "description": self.description,
            "image_url": self.image_url,
            "status": self.status,
            "sale_price": self.sale_price,
            "sold_date": self.sold_date.isoformat() if self.sold_date else None,
        }


# ─────────────────────────────────────────────────────────────────────────────
# LEAD MODEL (Feature 2: Customer Interest & Lead Management)
# ─────────────────────────────────────────────────────────────────────────────
# The Lead model stores potential customer inquiries.
# When a customer clicks "Show Interest" on a car listing, their contact
# information is captured here for follow-up by the admin.
#
# This solves the problem of losing potential customers who are interested
# but not ready to visit immediately.
class Lead(db.Model):
    __tablename__ = "lead"
    
    # Primary key - unique identifier for each lead
    lead_id = db.Column(db.Integer, primary_key=True)
    
    # Customer's name for personalized follow-up
    name = db.Column(db.String(100), nullable=False)
    
    # Customer's email - validated with regex before storing
    email = db.Column(db.String(120), nullable=False)
    
    # Optional message from the customer about their interest
    message = db.Column(db.Text, nullable=True)
    
    # Foreign key linking to the car they're interested in
    car_id = db.Column(db.Integer, db.ForeignKey('car.car_id'), nullable=False)
    
    # Timestamp when the lead was created
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    
    # Relationship to Car model for easy access to car details
    car = db.relationship('Car', backref=db.backref('leads', lazy=True))
    
    def to_dict(self):
        """
        Convert Lead to dictionary, including related car info.
        """
        return {
            "lead_id": self.lead_id,
            "name": self.name,
            "email": self.email,
            "message": self.message,
            "car_id": self.car_id,
            "car_model": self.car.model if self.car else None,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }


# ─────────────────────────────────────────────────────────────────────────────
# APPOINTMENT MODEL (Feature 3: Appointment Scheduling System)
# ─────────────────────────────────────────────────────────────────────────────
# The Appointment model stores scheduled test drive appointments.
# This prevents double-bookings and provides an organized view of upcoming
# appointments for the admin.
#
# Time slots are 1-hour blocks from 9 AM to 5 PM.
class Appointment(db.Model):
    __tablename__ = "appointment"
    
    # Primary key - unique identifier for each appointment
    appointment_id = db.Column(db.Integer, primary_key=True)
    
    # Customer details
    customer_name = db.Column(db.String(100), nullable=False)
    customer_email = db.Column(db.String(120), nullable=False)
    customer_phone = db.Column(db.String(20), nullable=True)
    
    # Foreign key linking to the car for the test drive
    car_id = db.Column(db.Integer, db.ForeignKey('car.car_id'), nullable=False)
    
    # Appointment date and time - stored as DateTime for easy comparison
    appointment_date = db.Column(db.Date, nullable=False)
    appointment_time = db.Column(db.Time, nullable=False)
    
    # Status: 'scheduled', 'completed', 'cancelled'
    status = db.Column(db.String(20), nullable=False, default='scheduled')
    
    # Timestamp when the appointment was created
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    
    # Relationship to Car model
    car = db.relationship('Car', backref=db.backref('appointments', lazy=True))
    
    def to_dict(self):
        """
        Convert Appointment to dictionary for JSON serialization.
        """
        return {
            "appointment_id": self.appointment_id,
            "customer_name": self.customer_name,
            "customer_email": self.customer_email,
            "customer_phone": self.customer_phone,
            "car_id": self.car_id,
            "car_model": self.car.model if self.car else None,
            "appointment_date": self.appointment_date.isoformat() if self.appointment_date else None,
            "appointment_time": self.appointment_time.strftime("%H:%M") if self.appointment_time else None,
            "status": self.status,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }


# ─────────────────────────────────────────────────────────────────────────────
# SAVED CAR MODEL (Customer's Garage)
# ─────────────────────────────────────────────────────────────────────────────
# Links customers to cars they've saved to their garage.
# This replaces the localStorage approach when customers are logged in,
# allowing their saved cars to persist across devices.
class SavedCar(db.Model):
    __tablename__ = "saved_car"
    
    # Composite primary key - customer_id + car_id
    id = db.Column(db.Integer, primary_key=True)
    
    # Foreign key to customer
    customer_id = db.Column(db.Integer, db.ForeignKey('customer.customer_id'), nullable=False)
    
    # Foreign key to car
    car_id = db.Column(db.Integer, db.ForeignKey('car.car_id'), nullable=False)
    
    # When the car was saved
    saved_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    
    # Relationships
    customer = db.relationship('Customer', backref=db.backref('saved_cars', lazy=True))
    car = db.relationship('Car', backref=db.backref('saved_by', lazy=True))
    
    # Ensure a customer can only save a car once
    __table_args__ = (db.UniqueConstraint('customer_id', 'car_id', name='unique_customer_car'),)
    
    def to_dict(self):
        return {
            "id": self.id,
            "customer_id": self.customer_id,
            "car_id": self.car_id,
            "car": self.car.to_dict() if self.car else None,
            "saved_at": self.saved_at.isoformat() if self.saved_at else None,
        }


# ─────────────────────────────────────────────────────────────────────────────
# SETTINGS MODEL (Email Configuration)
# ─────────────────────────────────────────────────────────────────────────────
# Stores application settings like email configuration.
# Uses key-value pairs for flexibility.
class Setting(db.Model):
    __tablename__ = "setting"
    
    # Setting key (e.g., 'mail_username', 'mail_password')
    key = db.Column(db.String(50), primary_key=True)
    
    # Setting value
    value = db.Column(db.Text, nullable=True)
    
    @staticmethod
    def get(key, default=None):
        """Get a setting value by key."""
        setting = Setting.query.get(key)
        return setting.value if setting else default
    
    @staticmethod
    def set(key, value):
        """Set a setting value."""
        setting = Setting.query.get(key)
        if setting:
            setting.value = value
        else:
            setting = Setting(key=key, value=value)
            db.session.add(setting)
        db.session.commit()
